[package]
name = "adent1a"
version = "0.1.0"
authors = ["Jack Mott <jack.mott@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = {path="../utils"}
petgraph = "*"

